title: "John Doe â€” Data Science"
description: "Production-like data engineering builds, explained clearly."
baseurl: ""
url: ""
markdown: kramdown
theme: null
plugins: []
defaults:
  - scope: { path: "" }
    values:
      layout: default
author: "John Doe"
github_username: "scalarmikeman"
youtube_channel: "@dataslinger6379"
medium_username: "dataslinger"
exclude:
  - "README.md"
